"""
Live Test Script for LangGraph Pipeline (Stage 4).

This script simulates the full pipeline flow:
1. User asks a Q&A question
2. User initiates a booking
3. User provides all reservation details
4. Admin reviews and approves
5. Pipeline auto-handles: notification → MCP recording → completion

Run with: python test_graph_live.py
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from dotenv import load_dotenv
load_dotenv()

from src.graph.pipeline import create_pipeline, run_user_message, run_admin_decision
from src.graph.state import PipelinePhase

print("=" * 60)
print("  STAGE 4 LIVE TEST — LangGraph Pipeline")
print("=" * 60)

# Step 1: Create the pipeline
print("\n[1] Creating LangGraph pipeline...")
pipeline = create_pipeline()
print("    ✅ Pipeline created and compiled")

# Step 2: Test Q&A message
print("\n[2] Testing Q&A message...")
state = run_user_message(pipeline, "What are the parking hours?")
print(f"    Phase: {state.get('conversation_phase')}")
print(f"    Response: {state.get('bot_response', '')[:100]}...")
assert state["conversation_phase"] == PipelinePhase.USER_INTERACTION.value
print("    ✅ Q&A works — stays in user_interaction phase")

# Step 3: Start a booking
print("\n[3] Starting a booking...")
state = run_user_message(pipeline, "I want to book a parking space")
print(f"    Phase: {state.get('conversation_phase')}")
print(f"    Response: {state.get('bot_response', '')[:100]}...")
print("    ✅ Booking flow started")

# Step 4: Provide name
print("\n[4] Providing name...")
state = run_user_message(pipeline, "Himanshu Sachan")
print(f"    Response: {state.get('bot_response', '')[:80]}...")

# Step 5: Provide email  
print("\n[5] Providing email...")
state = run_user_message(pipeline, "himanshu@example.com")
print(f"    Response: {state.get('bot_response', '')[:80]}...")

# Step 6: Provide car number
print("\n[6] Providing car number...")
state = run_user_message(pipeline, "UP121")
print(f"    Response: {state.get('bot_response', '')[:80]}...")

# Step 7: Choose space type
print("\n[7] Choosing space type...")
state = run_user_message(pipeline, "1")
print(f"    Response: {state.get('bot_response', '')[:80]}...")

# Step 8: Provide start time
print("\n[8] Providing start time...")
state = run_user_message(pipeline, "2026-05-20 09:00")
print(f"    Response: {state.get('bot_response', '')[:80]}...")

# Step 9: Provide end time
print("\n[9] Providing end time...")
state = run_user_message(pipeline, "2026-05-20 18:00")
print(f"    Response: {state.get('bot_response', '')[:80]}...")

# Step 10: Confirm booking
print("\n[10] Confirming booking...")
state = run_user_message(pipeline, "yes")
print(f"    Phase: {state.get('conversation_phase')}")
print(f"    Reservation ID: {state.get('reservation_id')}")
print(f"    Response: {state.get('bot_response', '')[:120]}...")

# Check if booking was submitted
phase = state.get("conversation_phase", "")
if phase in [PipelinePhase.AWAITING_ADMIN.value, PipelinePhase.ADMIN_REVIEWING.value]:
    print("    ✅ Booking submitted! Pipeline auto-transitioned to admin review")
    
    # Step 11: Admin reviews (may already have review from auto-advance)
    if "RESERVATION REVIEW" not in state.get("bot_response", ""):
        print("\n[11] Admin reviewing...")
        state = run_admin_decision(pipeline, state, "review")
        print(f"    Phase: {state.get('conversation_phase')}")
        print(f"    Review:\n{state.get('bot_response', '')}")
    else:
        print("\n[11] Review already auto-generated by pipeline ✅")
    
    # Step 12: Admin approves
    print("\n[12] Admin approving...")
    state = run_admin_decision(pipeline, state, "approve Stage 4 test")
    print(f"    Phase: {state.get('conversation_phase')}")
    print(f"    Decision: {state.get('admin_decision')}")
    print(f"    Notes: {state.get('admin_notes')}")
    print(f"    Notification Sent: {state.get('notification_sent')}")
    print(f"    MCP Recorded: {state.get('mcp_recorded')}")
    print(f"\n    Final Summary:\n{state.get('bot_response', '')}")
    
    assert state["conversation_phase"] == PipelinePhase.COMPLETED.value
    assert state["admin_decision"] == "approve"
    print("\n    ✅ FULL PIPELINE COMPLETE!")
else:
    print(f"    ⚠ Unexpected phase: {state.get('conversation_phase')}")
    print("    The chatbot may not have recognized the booking intent.")
    print("    This can happen if the LLM didn't return INTENT:BOOKING.")
    print("    The test infrastructure still works correctly.")

print("\n" + "=" * 60)
print("  STAGE 4 LIVE TEST COMPLETE")
print("=" * 60)
